config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  namespace :dashboard do
    get 'home'
    get 'profile'
    get 'vote'
    resources :moves
    resources :monsters
    resources :items
  end

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'dashboard#home', as: :authenticated_root
    end
  end

  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/monster.rb
# == Schema Information
#
# Table name: monsters
#
#  id         :integer          not null, primary key
#  name       :string           default(""), not null
#  level      :integer          default(1), not null
#  max_hp     :integer          default(1), not null
#  current_hp :integer          default(1), not null
#  experience :integer          default(1), not null
#  stats      :string           default("---\n- 0\n- 0\n- 0\n- 0\n- 0\n- 0\n")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Monster < ActiveRecord::Base
end

app/models/move.rb
class Move < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard/items_controller.rb
class Dashboard::ItemsController < DashboardController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to dashboard_items_path, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to dashboard_items_path, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :health)
    end
end

app/controllers/dashboard/monsters_controller.rb
class Dashboard::MonstersController < DashboardController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]
  
  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to dashboard_monsters_path, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to dashboard_monsters_path, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:name, :experience, :max_hp, :level)
    end
end

app/controllers/dashboard/moves_controller.rb
class Dashboard::MovesController < DashboardController
  before_action :set_move, only: [:show, :edit, :update, :destroy]
  
  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to dashboard_moves_path, notice: 'Move was successfully created.' }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to dashboard_moves_path, notice: 'Move was successfully updated.' }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: 'Move was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_params
        params.require(:move).permit(:name, :power)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def profile
    @profile = current_user
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/home.html.erb
<h1>News Feed</h1>

app/views/dashboard/items/_form.html.erb
<%= form_for [:dashboard, @item] do |f| %>

  <div class="form-group">
  <%= f.label :name, 'Name', class: 'col-sm-1' %>
   <div class="col-sm-2">
    <%= f.text_field :name, class: 'form-control col-sm-4 inline'%>
    </div>
  </div>

  <div class="form-group ">
    <%= f.label :health, class: 'col-sm-1' %>
    <div class="col-sm-2">
      <%= f.text_field :health, class: 'form-control inline'%>
    </div>
  </div>

  <div class="form-group ">
  <%= f.label :description,  class: 'col-sm-1' %>
  <div class="col-sm-2">
      <%= f.text_field :description, class: 'form-control inline'%>
  </div>

  </div>


  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

app/views/dashboard/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/dashboard/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<div id="new-monster-title">
  <h3>Click here to upload your own item</h3>
  <%= link_to 'New Item', new_dashboard_item_path, class: 'btn btn-primary'  %>
</div>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>


      <tr>
        <td>
          <%= image_tag 'slug.gif', size: "200" %>
        </td>
        <td>
        <span> Name: </span><%= item.name %>
        <br>
        <span> health: </span><%= item.health %>
        <br>
        <span> description: </span><%= item.description %>
        <br>

       </td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/dashboard/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboard_items_path %>

app/views/dashboard/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/dashboard/monsters/_form.html.erb
<%= form_for [:dashboard, @monster] do |f| %>

  <div class="form-group">
  <%= f.label :name, 'Name', class: 'col-sm-1' %>
   <div class="col-sm-2">
    <%= f.text_field :name, class: 'form-control col-sm-4 inline'%>
    </div>
  </div>

  <div class="form-group ">
    <%= f.label :level, 'level', class: 'col-sm-1' %>
    <div class="col-sm-2">
      <%= f.text_field :level, class: 'form-control inline'%>
    </div>
  </div>

  <div class="form-group ">
  <%= f.label :experience, 'experience', class: 'col-sm-1' %>
  <div class="col-sm-2">
      <%= f.text_field :experience, class: 'form-control inline'%>
  </div>

  </div>
  <div class="form-group ">
    <%= f.label :max_hp, 'max hp', class: 'col-sm-1' %>
    <div class="col-sm-2">
      <%= f.text_field :max_hp, class: 'form-control inline'%>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

app/views/dashboard/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form' %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/dashboard/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monsters</h1>


<div id="new-monster-title">
  <h3>Click here to upload your own monster</h3>
  <%= link_to 'New Monster', new_dashboard_monster_path, class: 'btn btn-primary' %>

</div>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monsters.each do |monster| %>


      <tr>
        <td>
          <%= image_tag 'slug.gif', size: "200" %>
        </td>
        <td>
        <span> Name: </span><%= monster.name %>
        <br>
        <span> Level: </span><%= monster.level %>
        <br>
        <span> Hp: </span><%= monster.current_hp %> / <%= monster.max_hp %>
        <br>
        <span> Experience: </span><%= monster.experience %>
        <br>
        <span> Strength: </span><%= monster.stats[1] %>
        <br>
        <span> Defense: </span><%= monster.stats[4] %>
        <br>
        <span> Speed: </span><%= monster.stats[7] %>
        <br>
        <span> Evasion: </span><%= monster.stats[10] %>
        <br>
        <span> Elemental: </span><%= monster.stats[13] %>
        <br>
       </td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/dashboard/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboard_monsters_path %>

app/views/dashboard/monsters/show.html.erb
<span> Name: </span><%= @monster.name %>
<br>
<span> Level: </span><%= @monster.level %>
<br>
<span> Hp: </span><%= @monster.current_hp %> / <%= @monster.max_hp %>
<br>
<span> Experience: </span><%= @monster.experience %>
<br>
<span> Strength: </span><%= @monster.stats[1] %>
<br>
<span> Defense: </span><%= @monster.stats[4] %>
<br>
<span> Speed: </span><%= @monster.stats[7] %>
<br>
<span> Evasion: </span><%= @monster.stats[10] %>
<br>
<span> Elemental: </span><%= @monster.stats[13] %>
<br>



<%= link_to 'Edit', edit_dashboard_monster_path(@monster) %> |
<%= link_to 'Back', dashboard_monsters_path %>

app/views/dashboard/moves/_form.html.erb
<%= form_for [:dashboard, @move] do |f| %>

  <div class="form-group">
  <%= f.label :name, 'Name', class: 'col-sm-1' %>
   <div class="col-sm-2">
    <%= f.text_field :name, class: 'form-control col-sm-4 inline'%>
    </div>
  </div>

  <div class="form-group ">
    <%= f.label :power, class: 'col-sm-1' %>
    <div class="col-sm-2">
      <%= f.text_field :power, class: 'form-control inline'%>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

app/views/dashboard/moves/edit.html.erb
<h1>Editing Move</h1>

<%= render 'form' %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/dashboard/moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moves</h1>

<div id="new-monster-title">
  <h3>Click here to upload your own move</h3>

  <%= link_to 'New Move', new_dashboard_move_path, class: 'btn btn-primary'  %>

</div>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
    <tr>
      <td>
        <%= image_tag 'slug.gif', size: "200" %>
      </td>
      <td>
      <span> Name: </span><%= move.name %>
      <br>
      <span> power: </span><%= move.power %>
      <br>


     </td>


    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/dashboard/moves/new.html.erb
<h1>New Move</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboard_moves_path %>

app/views/dashboard/moves/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>

app/views/dashboard/profile.html.erb
<h1> <%= @profile.email %> </h1>

app/views/dashboard/vote.html.erb
<h1>This is the screen where the voting happens</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeoGame</title>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">Geo Monsters</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <a class="page-scroll" href="#services">Glossary</a>
        </li>
        <li>
          <a class="page-scroll" href="#portfolio">Contribute</a>
        </li>
        <li>
          <a class="page-scroll" href="#about">About</a>
        </li>
        <li>
          <a class="page-scroll" href="#contact">Contact</a>
        </li>
        <li>
          <% if current_user %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
              <%= link_to "Login", new_user_session_path %>
          <% end %>

        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>



    <%= yield %>




</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeoGame</title>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse sidebar" role="navigation">
    <div class="container-fluid">

		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Geo Monsters</a>
		</div>

		<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="active"><a href="/dashboard/home">Home<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-home"></span></a></li>
				<li ><a href="/dashboard/profile">Profile<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a></li>
				<li ><a href="/dashboard/monsters">Monsters<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-fire"></span></a></li>
				<li><a href="/dashboard/items">Items<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-leaf"></span></a></li>
				<li ><a href="/dashboard/moves">Moves<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-screenshot"></span></a></li>
				<li ><a href="/dashboard/vote">Vote<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-ok"></span></a></li>
        <li ><%= link_to "Sign out", destroy_user_session_path, method: :delete %></span></a></li>
			</ul>
		</div>
	</div>
</nav>

<div class="main">
  <%= yield %>
</div>


</body>
</html>